config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :records do
    member do
      get :download_all_files
    end
  end

  namespace :users do
    resource :profile
  end

  root 'home#index'
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/record.rb
class Record < ApplicationRecord
  searchkick

  belongs_to :user

  has_and_belongs_to_many :tags
  has_and_belongs_to_many :softwares
  has_many_attached :files
  has_many_attached :images

  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 150 }

  def search_data
    {
      name: title,
      tags: tags.map(&:name),
      softwares: softwares.map(&:name),
      user_name: user.full_name,
      user_username: user.username
    }
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect { |s| s.strip.downcase }.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end

  def tag_list
    self.tags.map(&:name).join(", ")
  end

  def software_list=(softwares_string)
    software_names = softwares_string.split(",").collect { |s| s.strip.downcase }.uniq
    new_or_found_softwares = software_names.collect { |name| Software.find_or_create_by(name: name) }
    self.softwares = new_or_found_softwares
  end

  def software_list
    self.softwares.map(&:name).join(", ")
  end
end

app/models/software.rb
class Software < ApplicationRecord
  has_and_belongs_to_many :records
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :records

  validates :name, presence: true, uniqueness: true, length: { in: 2..10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable

  has_many :records, dependent: :destroy
  has_one_attached :avatar

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    if params[:query].present?
      @records = Record.search(params[:query])
    else
      @records = filter_records(params[:tags], params[:softwares])
    end
  end

  private

  def filter_records(selected_tags, selected_softwares)
    records = Record.all

    # Filter by tags if provided
    if selected_tags.present?
      records = records.joins(:tags)
                       .where(tags: { name: selected_tags })
                       .group("records.id")
                       .having("COUNT(tags.id) = ?", selected_tags.size)
    end

    # Filter by software if provided
    if selected_softwares.present?
      records = records.joins(:softwares)
                       .where(softwares: { name: selected_softwares })
                       .group("records.id")
                       .having("COUNT(softwares.id) = ?", selected_softwares.size)
    end

    records
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new ]

  def index
    if params[:tag]
      @records = Record.joins(:tags).where(tags: { name: params[:tag] }).distinct
      @tag = Tag.find_by(name: params[:tag])
    else
      @records = Record.all
    end
  end

  def show
    @record = Record.find(params[:id])
    @user_records = Record.where(user_id: @record.user_id).where.not(id: @record.id)
  end

  def new
    @record = Record.new(user: current_user)
  end

  def edit

  end

  def create
    @record = current_user.records.build(record_params)

      if @record.save
        redirect_to @record, notice: "Record was successfully created."
      else
        render :new
      end
  end

  def update
    if @record.update(record_params)
      redirect_to @record, notice: 'Record was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @record.destroy
    redirect_to records_url, notice: 'Record was successfully destroyed.'
  end

  private

  def set_record
    @record = Record.find(params[:id])
  end

  def record_params
    params.require(:record).permit(:title, :description, :user_id, :tag_list, :software_list, files: [], images: [])
  end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  before_action :set_user

  def show
    @records = @user.records.order(created_at: :desc)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :username, :first_name, :last_name, :position, :avatar])
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:avatar])
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def all_tags
    Tag.all
  end

  def all_softwares
    Software.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/users/profiles_helper.rb
module Users::ProfilesHelper
end

app/views/home/_album.html.erb
<div class="album py-5 bg-body-tertiary">
  <div class="container ">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3">

      <% @records.each do |record| %>
        <%= render record %>
      <% end %>

    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= render "shared/navbar" %>
<%= render "shared/album" %>

app/views/home/partials/_album.html.erb
<div class="album py-5 bg-body-tertiary">
  <div class="container ">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3">
      <%= render partial: "records/record", collection: @records %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-bs-theme="dark">
  <head>
    <title>CadCatalog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/records/_form.html.erb
<%= form_with(model: record) do |form| %>
  <% if record.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
        <% record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="d-flex justify-content-center">
    <div class="col-lg-5">
      <h4 class="mb-3">Create record:</h4>
      <form class="needs-validation" novalidate="">
        <div class="row g-3">
          <div class="col-12">
            <%= form.label :title, class: "form-label" %>
            <%= form.text_field :title, class: "form-control" %>
          </div>

          <div class="col-12">
            <%= form.label :description, class: "form-label" %>
            <%= form.text_area :description, class: "form-control" %>
          </div>

          <div class="col-md-5">
            <label for="country" class="form-label">Upload:</label>
            <input type="text" class="form-control" id="zip" placeholder="">
          </div>

          <div class="col-md-4">
            <label for="state" class="form-label">Image</label>
            <input type="text" class="form-control" id="zip" placeholder="">
          </div>

          <div class="col-md-3">
            <label for="zip" class="form-label">Tags:</label>
            <input type="text" class="form-control" id="zip" placeholder="">
          </div>
        </div>

        <hr class="my-4">

        <%= form.submit "Save", class: "w-100 btn btn-primary btn-lg"%>

      </form>
    </div>
  </div>
<% end %>

app/views/records/_record.html.erb
<div class="col">
  <div class="card shadow-sm h-100">
    <div class="card-img-top overflow-hidden" style="height: 150px;">
      <% if record.images.attached? %>
        <%= image_tag record.images.first, class: "w-100 h-100 object-cover" %> <!-- Full width, full height, cover object-fit -->
      <% else %>
        <svg class="w-100 h-100" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
          <rect width="100%" height="100%" fill="#55595c"></rect>
          <text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text>
        </svg>
      <% end %>
    </div>
    <div class="card-body d-flex flex-column">
      <%= link_to record.title, record_path(record), class: "card-title text-decoration-none" %>
      <p class="card-text text-body-secondary"><%= record.description %></p>
      <div class="mt-auto">
        <% record.tags.each do |tag| %>
          <%= link_to tag.name, records_path(tag: tag.name), class: "badge bg-secondary-subtle border border-secondary-subtle text-secondary-emphasis rounded-pill text-decoration-none me-1" %>
        <% end %>
      </div>
    </div>
    <%= link_to users_profile_path(id: record.user_id), class: "text-decoration-none" do %>
      <div class="card-footer d-flex justify-content-between">
        <small class="text-body-secondary">@<%= record.user.username %></small>
        <small class="text-body-secondary"><%= record.created_at.strftime("%d %b %H:%M") %></small>
      </div>
    <% end %>
  </div>
</div>

app/views/records/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Records for u tags:</h1>

<% if @tag %>
  <h2><%= @tag.name %></h2>
<% else %>
  <h2>All Records</h2>
<% end %>

<div class="album py-5 bg-body-tertiary">
  <div class="container ">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3">

      <% @records.each do |record| %>
        <%= render record %>
      <% end %>

    </div>
  </div>
</div>

app/views/records/new.html.erb
<div class="py-5 text-center container">
  <img class="d-block mx-auto mb-4" src="/docs/5.3/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
  <h2>Upload file:</h2>
  <p class="lead">Below is an example form built entirely with Bootstrap’s form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.</p>
</div>
<%= render "records/partials/form", record: @record %>

app/views/records/partials/_carousel.html.erb
<div class="d-flex justify-content-center">
  <div id="myCarousel" class="carousel w-75 slide mb-6 pt-5 d-flex justify-content-center align-items-center">
  <!-- Carousel Indicators -->
  <div class="carousel-indicators">
    <% record.images.each_with_index do |image, index| %>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="<%= index %>"
              class="<%= 'active' if index.zero? %>"
              aria-label="Slide <%= index + 1 %>"
              <%= 'aria-current="true"' if index.zero? %>></button>
    <% end %>
  </div>

  <!-- Carousel Inner -->
  <div class="carousel-inner" style="height: 600px; width: 800px" > <!-- Set fixed height for carousel -->
    <% record.images.each_with_index do |image, index| %>
      <div class="carousel-item <%= 'active' if index.zero? %>" style="height: 100%;"> <!-- Carousel item matches fixed height -->
        <%= image_tag image, class: "d-block w-100 h-100", alt: "Slide #{index + 1}" %>
      </div>
    <% end %>
  </div>

    <!-- Carousel Controls -->
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

app/views/records/partials/_form.html.erb
<%= form_with(model: record) do |form| %>
  <% if record.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
        <% record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="d-flex justify-content-center container">
    <div class="col-lg-5">
      <h4 class="mb-3">Create record:</h4>
      <form class="needs-validation" novalidate="">
        <div class="row g-3">
          <div class="col-12">
            <%= form.label :title, class: "form-label" %>
            <%= form.text_field :title, class: "form-control" %>
          </div>

          <div class="col-12">
            <%= form.label :description, class: "form-label" %>
            <%= form.text_area :description, class: "form-control" %>
          </div>

          <div class="col-md-5">
            <%= form.label :file, class: "form-label" %>
            <%= form.file_field :files, multiple: true, class: "form-control" %>
          </div>

          <div class="col-md-4">
            <%= form.label :images, class: "form-label" %>
            <%= form.file_field :images, multiple: true, class: "form-control" %>
          </div>

          <div class="col-md-3">
            <%= form.label :tag_list, class: "form-label" %>
            <%= form.text_field :tag_list, value: @record.tags.map(&:name).join(", "), class: "form-control" %>
          </div>
        </div>

        <hr class="my-4">

        <%= form.submit "Save", class: "w-100 btn btn-primary btn-lg"%>

      </form>
    </div>
  </div>
<% end %>

app/views/records/partials/_table.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Upload at:</th>
    <th>Download:</th>
  </tr>
  </thead>
  <tbody>
  <% (@record.files + @record.images).each do |attachment| %>
    <tr>
      <td><%= link_to attachment.filename.to_s, rails_blob_path(attachment), class: "text-decoration-none" %></td>
      <td><%= attachment.content_type %></td>
      <td><%= attachment.created_at.strftime("%B %dth, %Y") %></td>
      <td>
        <%= link_to 'Download', rails_blob_path(attachment, disposition: 'attachment'), class: 'btn btn-outline-secondary btn-sm' %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/records/show.html.erb
<%= render "records/partials/carousel", record: @record %>
<div class="container-sm pt-5">
  <div class="row g-5">
    <div class="col-md-8">
      <h3 class="pb-4 mb-4 border-bottom">
        <%= @record.title %>
      </h3>
      <div>
        <%= @record.description %>
      </div>
      <h4 class="mt-5">Files (<%= @record.files.count %>)</h4>
      <%= render "records/partials/table" %>
    </div>

    <div class="col-md-4">
      <div class="position-sticky" style="top: 2rem;">
        <div class="p-4 mb-3 bg-body-tertiary rounded">
          <h5 class="mb-0">Details</h5>
          <div class="row">
            <div class="col-4"><strong>Uploaded:</strong></div>
            <div class="col-6"><%= @record.created_at.strftime("%B %d, %Y") %></div>
          </div>
          <div class="row">
            <div class="col-4"><strong>Software:</strong></div>
            <div class="col-6"><%= @record.software_list %></div>
          </div>
          <div class="row">
            <div class="col-4"><strong>Tags:</strong></div>
            <div class="col-6"><%= @record.tag_list %></div>
          </div>
        </div>


        <div>
          <h4 class="fst-italic">More from @<%= link_to @record.user.username, users_profile_path(id: @record.user_id) %></h4>
          <ul class="list-unstyled">
            <% @user_records.last(3).each do |user_record| %>
              <li>
                <%= link_to record_path(user_record), class: "d-flex flex-column flex-lg-row gap-3 align-items-start align-items-lg-center py-3 link-body-emphasis text-decoration-none border-top" do %>
                  <%= image_tag user_record.images.first, class: "bd-placeholder-img", width: "100%", height: "96" %>
                  <div class="col-lg-8">
                    <h6 class="mb-0"><%= user_record.title %></h6>
                    <small class="text-body-secondary"><%= user_record.created_at.strftime("%d %B %Y") %></small>
                  </div>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_album.html.erb
<div class="album">
  <div class="container ">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4 g-3">
      <%= render partial: "records/record", collection: @records %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="mb-3 mb-md-0 text-body-secondary">© 2024 Company, Inc</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
    </ul>
  </footer>
</div>

app/views/shared/_header.html.erb
<header class="p-3 border-bottom">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

      <%= link_to 'CATALOG', root_path, class: 'd-flex align-items-center mb-2 me-5 mb-lg-0 text-decoration-none fs-3 fw-bold' %>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="#" class="nav-link px-2 link-secondary">Overview</a></li>
        <li><a href="#" class="nav-link px-2 link-body-emphasis">Inventory</a></li>
        <li><a href="#" class="nav-link px-2 link-body-emphasis">Customers</a></li>
        <li><a href="#" class="nav-link px-2 link-body-emphasis">Products</a></li>
      </ul>

      <% if user_signed_in? %>
        <div class="dropdown text-end">
          <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false" >
            <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
          </a>
          <ul class="dropdown-menu text-small">
            <li><%= link_to 'My Profile', users_profile_path(id: current_user.id), class: 'dropdown-item' %></li>
            <li><%= link_to 'New Record', new_record_path, class: 'dropdown-item' %></li>
            <li><%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %></li>
          </ul>
        </div>
      <% else %>
        <a><%= link_to 'Log In', new_user_session_path, class: 'nav-link px-2 link-body-emphasis' %></a>
        <a><%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link px-2 link-body-emphasis' %></a>
      <% end %>

    </div>
  </div>
</header>

app/views/shared/_navbar.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg" aria-label="Eleventh navbar example">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarsExample09">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Tags:</a>
            <ul class="dropdown-menu">
              <% all_tags.each do |tag| %>
                <% unless (params[:tags] || []).include?(tag.name) %>
                  <li>
                    <%= link_to tag.name, root_path(tags: (params[:tags] || []) + [tag.name], softwares: params[:softwares]), class: "dropdown-item text-decoration-none" %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Software:</a>
            <ul class="dropdown-menu">
              <% all_softwares.each do |software| %>
                <% unless (params[:softwares] || []).include?(software.name) %>
                  <li>
                    <%= link_to software.name, root_path(softwares: (params[:softwares] || []) + [software.name], tags: params[:tags]), class: "dropdown-item text-decoration-none" %>
                  </li>
                <% end %>
              <% end %>
            </ul>
          </li>
        </ul>
        <div class="container-lg">
          <% (params[:tags] || []).each do |tag| %>
            <%= link_to "#{tag} ×", root_path(tags: (params[:tags] || []).reject { |t| t == tag }, softwares: params[:softwares]), class: "btn btn-outline-secondary btn-sm ms-2" %>
          <% end %>

          <% (params[:softwares] || []).each do |software| %>
            <%= link_to "#{software} ×", root_path(softwares: (params[:softwares] || []).reject { |s| s == software }, tags: params[:tags]), class: "btn btn-outline-secondary btn-sm ms-2" %>
          <% end %>
        </div>

        <%= form_with url: root_path, method: :get, local: true do |form| %>
          <%= form.text_field :query, placeholder: "Search", class: "form-control" %>
        <% end %>
      </div>
    </div>
  </nav>
</div>

app/views/users/profiles/show.html.erb
<div class="mb-5">
  <div class="p-5 bg-body-tertiary">
    <div class="container py-5 d-flex justify-content-start align-items-center">
        <%= image_tag @user.avatar %>
      <div class="ms-4">
        <p class="mb-0 fs-1"><%= @user.full_name %></p>
        <p class="text-body-secondary fs-4 fw-lighter"><%= @user.position %></p>
      </div>
    </div>
  </div>
</div>
<%= render partial: "shared/album" %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>